name: Check Version

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Replace with your Python version

    - name: Install toml package
      run: |
        python -m pip install toml

    - name: Check pyproject.toml version
      run: |
        TAG=${GITHUB_REF#refs/tags/}
        PYPROJECT_VERSION=$(python -c "import toml; pyproject = toml.load('pyproject.toml'); print(pyproject['project']['version'])")
        if [ "$TAG" != "v$PYPROJECT_VERSION" ]; then
          echo "Tag version ($TAG) does not match pyproject.toml version ($PYPROJECT_VERSION)"
          exit 1
        fi
