name: Check Version

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Replace with your Python version

    - name: Check setup.py version
      run: |
        TAG=${GITHUB_REF#refs/tags/}
        SETUP_PY_VERSION=$(python setup.py --version)
        if [ "$TAG" != "$SETUP_PY_VERSION" ]; then
          echo "Tag version ($TAG) does not match setup.py version ($SETUP_PY_VERSION)"
          exit 1
        fi
