name: Update Formula

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true

jobs:
  update-formula:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Use the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Update formula
      run: |
        TAG=${{ github.event.inputs.tag }}
        FORMULA_FILE="Formula/dirmapper.rb"
        
        # Fetch the tarball URL and SHA256 checksum
        REPO="nashdean/dirmap"
        TAR_URL="https://github.com/$REPO/archive/refs/tags/$TAG.tar.gz"
        SHA256=$(curl -L $TAR_URL | sha256sum | awk '{ print $1 }')
        
        # Update the formula file
        sed -i "s|^  url \".*\"|  url \"$TAR_URL\"|" $FORMULA_FILE
        sed -i "s|^  sha256 \".*\"|  sha256 \"$SHA256\"|" $FORMULA_FILE

        # Commit and push changes
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add $FORMULA_FILE
        git commit -m "Update dirmapper formula to $TAG"
        git push
